name: Docker Image CI

on:
  push:
    branches: [ "i201826" ]


jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env: 
        DOCKER_USER:  ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag runtimeterrorss1/ca4-webserver:latest
    - name: Docker push
      run: docker push runtimeterrorss1/ca4-webserver:latest
