name: Docker Image CI

on:
  push:
    branches: [ "i201826" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: runtimeterrorss1
        password: runtimeterrors1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag runtimeterrorss1/CA4:latest
    - name: Push Docker Image
      run: docker push runtimeterrorss1/CA4:latest

